---

- name: Run docker-watchtower
  docker:
    command: "{{watchtower_options}} {{watchtower_follow}}"
    image: "{{watchtower_image}}"
    name: watchtower
    restart_policy: always
    state: reloaded
    volumes: "{{watchtower_volumes}}"
