---

- name: Run docker-watchtower
  docker:
    command: "{{watchtower_options}} {{watchtower_follow}}"
    image: "{{watchtower_image}}"
    name: watchtower
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
