---
- name: Run docker-watchtower
  docker_container:
    command: "{{watchtower_options}} {{watchtower_follow}}"
    image: "{{watchtower_image}}"
    name: watchtower
    restart_policy: always
    restart: true
    volumes: "{{watchtower_volumes}}"
